[deploy]
builder = "RAILPACK"
watchPatterns = ["abc"]
buildCommand = "pnpm run build"
buildEnvironment = "V2"
dockerfilePath = "abc"
nixpacksConfigPath = "def"
nixpacksPlan = {}
healthcheckTimeout = 100
healthcheckPath = "/health"
startCommand = "pnpm run dev"
restartPolicyType = "NEVER"
sleepApplication = true
multiRegionConfig = {
  localhost = {
    numReplicas = 2
  }
}
runtime = "V2"
